config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  resources :questions do
    resources :answers do
      patch :select, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :attachments, only: [:destroy]

  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  root to: "questions#index"

  mount ActionCable.server => "/cable"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  get "/search" => "search#search"
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :subscribe

  def is_author?(user)
    user.id == user_id
  end

  def select_answer(answer)
    ActiveRecord::Base.transaction do
      answers.update_all(best: false)
      answer.update!(best: true)
    end
  end

  def subscribe
    self.subscriptions.create(user_id: self.user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: BasicQuestionSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question, serializer: BasicQuestionSerializer
  end

  private

    def question_params
      params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question, only: [:show, :destroy, :update]
  before_action :load_current_user
  before_action :build_answer, only: [:show]
  before_action :load_gon_question, only: [:show]

  after_action :publish_question, only: [:create]

  respond_to :js, only: [:show, :update]

  authorize_resource


  def new
    respond_with(@question = Question.new)
  end

  def create
    @question = current_user.questions.create(question_params)
    respond_with @question
  end

  def show
    @answers = @question.answers.order(best: :desc)
    respond_with @question
  end

  def index
    respond_with(@questions = Question.all)
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

    def question_params
      params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
    end

    def load_question
      @question = Question.find(params[:id])
    end

    def build_answer
      @answer = @question.answers.new
    end

    def publish_question
      return unless @question.valid?
      ActionCable.server.broadcast(
        'questions',
        @question
        )
    end

    def load_current_user
      gon.user = current_user
    end

    def load_gon_question
      gon.question = @question
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @answers.each do |answer|
  - cache answer do
    - if answer.persisted?
      = render partial: "answers/edit_answer", locals: { answer: answer }

app/views/questions/_edit_question.html.slim
span class="question-#{question.id}"
  p= link_to question.title, question_path(question)
  - if can?(:edit, question)
        p= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: question.id }
        = render partial: "questions/form_question", locals: { question: question }

app/views/questions/_form_question.html.slim
p
  = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
    = f.label :title
    = f.text_field :title
    = f.label :body
    = f.text_area :body
    .question-errors
    = f.submit "Save"

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  .questions

    - @questions.each do |q|
      = render partial: "questions/edit_question", locals: { question: q }

  - if can?(:create, Question)
    p= link_to "Ask question", new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body

  p Attachments:
  .attachments
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render "attachment_fields", f: a
      = link_to_add_association 'Add file', f, :attachments

  p= f.submit 'Create'

app/views/questions/show.html.slim
- cache @question do
  div
    h1= - @question.title
    .question
      span class = "question-#{@question.id}"
        p= - @question.body
        p
          | Rating:
          span class="rating-#{@question.class.name.underscore}-#{@question.id}"
            =< @question.rating
        = render partial: "attachments", locals: { model: @question }


        -if user_signed_in?
          = render partial: "vote", locals: { model: @question }

          p
            = link_to "Subscribe", question_subscriptions_path(@question), remote: true, method: :post, class: "subscribe-link",style: "display: #{current_user.subscribed?(@question) ? 'none' : 'inline'}"
            = link_to "Unsubscribe", "/questions/#{@question.id}/subscriptions/#{current_user.subscribed?(@question) ? current_user.subscribed(@question).id : ''}", remote: true, method: :delete, class: "unsubscribe-link", style: "display: #{current_user.subscribed?(@question) ? 'inline' : 'none'}"


          -if can?(:destroy, @question)
            = link_to "Delete", question_path(@question), method: "delete"

        = render partial: "comments", locals: { model: @question }



  .answers
   = render "answers"

  = form_for [@question, @answer], remote: true do |f|
    = f.label :body
    .answer-errors
    = f.text_area :body
    p Attachments :
    p
    .attachments
      = f.fields_for :attachments, @answer.attachments.build do |a|
        = render "attachment_fields", f: a
        = link_to_add_association 'Add file', f, :attachments
    = f.submit "Answer"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |message| %>
        $('.question-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $(".question-<%= @question.id %>").replaceWith("<%= j render partial: 'questions/edit_question', locals: { question: @question } %>");
<% end %>