config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  resources :questions do
    resources :answers do
      patch :select, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :attachments, only: [:destroy]

  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  root to: "questions#index"

  mount ActionCable.server => "/cable"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  get "/search" => "search#search"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question, touch: true
  belongs_to :user

  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :informing


  def is_author?(user)
    user.id == user_id
  end

  def has_vote_from_user(user)
    votes.find_by(user_id: user.id)
  end

  def informing
    AnswerInformJob.perform_now(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question
  before_action :load_answer, only: [:show, :update, :destroy, :select]
  before_action :load_current_user

  after_action :publish_answer, only: [:create]

  respond_to :js

  def create
    authorize! :create, Answer
    @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    authorize! :update, @answer
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    authorize! :destroy, @answer
    respond_with @answer.destroy
  end

  def select
    authorize! :select, @question
    respond_with @question.select_answer(@answer)
  end

  private

    def load_question
      @question = Question.find(params[:question_id])
    end

    def answer_params
      params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
    end

    def load_answer
      @answer = Answer.find(params[:id])
    end

    def publish_answer
      return unless @answer.valid?
      answer = @answer.as_json
      answer[:rating] = @answer.rating
      answer[:question] = @answer.question
      answer[:attachments] = @answer.attachments.map {|a| { id: a.id, filename: a.file.filename, url: a.file.url , user_id: @answer.user_id } }
      ActionCable.server.broadcast(
        "questions/#{@question.id}/answers",
        answer
        )
    end

    def load_current_user
      gon.user = current_user
    end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: [:show]

  authorize_resource

  def index
    @answers = @question.answers
    respond_with @answers, each_serializer: BasicAnswerSerializer
  end

  def show
    respond_with @answer, serializer: AnswerSerializer
  end

  def create
    @answer = current_resource_owner.answers.create(answer_params.merge(question_id: @question.id))
    respond_with @answer, serializer: BasicAnswerSerializer, location: api_v1_question_answers_path
  end

  private

    def load_question
      @question = Question.find(params[:question_id])
    end

    def load_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_edit_answer.html.slim
span class="answer-#{answer.id}"
    div class=(answer.best ? "best_answer" : "other_answer")
      p= answer.body
      p
        | Rating:
        p class="rating-#{answer.class.name.underscore}-#{answer.id}"
          =< answer.rating

      = render partial: "attachments", locals: { model: answer }

    - if user_signed_in?
      = render partial: "vote", locals: { model: answer }

      - if can?(:select, @question)
        p= link_to "Select", select_question_answer_path(@question, answer), method: "patch", remote: true

      - if  can?(:edit, answer)
        p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= link_to "Delete", question_answer_path(@question, answer), method: "delete", remote: true
        p
          = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
            = f.label :body, "Answer"
            = f.text_area :body
            = f.submit "Save"

    = render partial: "comments", locals: { model: answer }

app/views/answers/destroy.js.erb
$(".answer-<%= @answer.id %>").remove();

app/views/answers/select.js.erb
$(".answers:first div").attr('class', 'other_answer');
$(".answer-<%= @answer.id %> div").attr('class', 'best_answer');
$(".answer-<%= @answer.id %>").prependTo(".answers:first");

app/views/answers/show.html.slim
div
 p= - @answer.body
 = link_to "Delete", question_answer_path(@question, @answer), method: "delete"

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $(".answer-<%= @answer.id %>").replaceWith("<%= j render partial: 'answers/edit_answer', locals: { answer: @answer } %>");
<% end %>