config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    post '/confirm_email' => 'omniauth_callbacks#confirm_email'
  end

  resources :questions do
    resources :answers do
      patch :select, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :attachments, only: [:destroy]

  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  root to: "questions#index"

  mount ActionCable.server => "/cable"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  get "/search" => "search#search"
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message, status: 403 }
      format.js { render "partials/errors", locals: { error: exception.message }, status: 403 }
      format.json { render json: [exception.message], status: 403 }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/views/application/_attachment_fields.html.slim
.nested-fields
  = f.label :file
  = f.file_field :file
  = link_to_remove_association "Remove file", f

app/views/application/_attachments.html.slim
div class="attachments_#{model.class.name.downcase}"
  ul
    -model.attachments.each do |a|
      span class="attachment-#{a.id}"
        li= link_to a.file.filename, a.file.url
        -if user_signed_in? and a.is_author?(current_user)
          p= link_to "Delete file", attachment_path(a), method: "delete", remote: true

app/views/application/_comments.html.slim
h5 comments to "#{model.class.name}"
.comments
  ul class="list-of-comments"
    -model.comments.order(id: :asc).each do |comment|
      - cache comment do
        li= comment.body

  p
    = form_for Comment.new, remote: true, html: { class: "comment-#{model.class.name.underscore}", id: "comment-#{model.class.name.underscore}-#{model.id}" } do |f|
      = f.hidden_field(:commentable_type, value: model.class.name)
      = f.hidden_field(:commentable_id, value: model.id)
      = f.label :body, "Comment"
      = f.text_area :body
      = f.submit "To comment"
-if user_signed_in?
  p= link_to 'Comment', '', class: "comment-#{model.class.name.underscore}-link", id: "comment-#{model.class.name.underscore}-#{model.id}"

app/views/application/_vote.html.slim
span class="vote-#{model.class.name.underscore}-#{model.id}"
  -unless model.is_author?(current_user)

    = link_to 'Reset', '#', class: "vote-link-reset", id: "vlr-#{model.class.name.underscore}-#{model.id}", data: { id: "#{ model.has_vote_from_user(current_user) ? model.has_vote_from_user(current_user).id : '' }" }, style: "display: #{ model.has_vote_from_user(current_user) ? 'inline' : 'none' }"

    = link_to '+1', '#', class: 'vote-link', id: "like-vl-#{model.class.name.underscore}-#{model.id}", data: { value: "1", votable_id: model.id, votable_type: "#{ model.class.name }" }, style: "display: #{ model.has_vote_from_user(current_user) ? 'none' : 'inline' }"

    = link_to '-1', '#', class: 'vote-link', id: "dislike-vl-#{model.class.name.underscore}-#{model.id}", data: { value: "-1", votable_id: model.id, votable_type: "#{ model.class.name }" }, style: "display: #{ model.has_vote_from_user(current_user) ? 'none' : 'inline' }"

app/views/application/enter_email.html.slim
= form_tag confirm_email_path do |f|
  p
    = label_tag :email
    = email_field_tag :email

  p= submit_tag 'Create'